CREATE TABLE `TASK_REQUESTS` (
	`ID`	BIGINT	NOT NULL,
	`USERS_ID`	BIGINT	NOT NULL,
	`DESCRIPTION`	TEXT	NOT NULL,
	`AMOUNT`	INT	NULL,
	`WORKING_DAY`	INT	NULL
);

CREATE TABLE `PAYMENTS` (
	`ID`	BIGINT	NOT NULL,
	`ORDERS_ID`	BIGINT	NOT NULL,
	`STATUS`	VARCHAR(20)	NULL,
	`PRICE`	BIGINT	NOT NULL
);

CREATE TABLE `DELIVERYS` (
	`ID`	BIGINT	NOT NULL,
	`ORDERS_ID`	BIGINT	NOT NULL,
	`CONTRCTS_ID`	BIGINT	NULL,
	`STATUS`	VARCHAR(100)	NULL,
	`DESTINATION`	VARCHAR(100)	NULL
);

CREATE TABLE `CONTRACTS` (
	`ID`	BIGINT	NOT NULL,
	`TASK_REQUEST_ID`	BIGINT	NOT NULL,
	`TASK_HOPE_ID`	BIGINT	NOT NULL,
	`AMOUNT`	INT	NOT NULL,
	`START_TIME`	TIMESTAMP	NOT NULL,
	`END_TIME`	TIMESTAMP	NOT NULL,
	`MAX_EDIT_COUNT`	INT	NULL,
	`PRICE_PER_ONE`	BIGINT	NOT NULL,
	`STATUS`	VARCHAR(100)	NOT NULL,
	`TYPE`	VARCHAR(100)	NOT NULL
);

CREATE TABLE `IMAGES` (
	`ID`	BIGINT	NOT NULL,
	`PRODUCTS_ID`	BIGINT	NULL,
	`TASK_REQUESTS_ID`	BIGINT	NULL,
	`FILE_NAME`	VARHCAR(100)	NOT NULL,
	`FILE_PATH`	VARCHAR(1024)	NOT NULL,
	`FILE_SIZE`	BIGINT	NOT NULL,
	`FILE_TYPE`	VARCHAR(50)	NOT NULL
);

CREATE TABLE `USERS` (
	`ID`	BIGINT	NOT NULL,
	`NICKNAME`	VARCHAR(100)	NOT NULL,
	`LOGINID`	VARCHAR(100)	NOT NULL,
	`PASSWORD`	VARCHAR(200)	NOT NULL,
	`KIND`	VARCHAR(20)	NOT NULL
);

CREATE TABLE `ORDERS` (
	`ID`	BIGINT	NOT NULL,
	`PRODUCTS_ID`	BIGINT	NOT NULL,
	`USERS_ID`	BIGINT	NOT NULL,
	`STATUS`	VARCHAR(100)	NOT NULL
);

CREATE TABLE `TASK_HOPES` (
	`ID`	BIGINT	NOT NULL,
	`TASK_REQUESTS_ID`	BIGINT	NOT NULL,
	`USERS_ID`	BIGINT	NOT NULL,
	`MIN_AMOUNT`	INT	NOT NULL,
	`MAX_EDIT_COUNT`	INT	NULL,
	`PRICE_PER_ONE`	BIGINT	NOT NULL,
	`DESCRIPTION`	TEXT	NOT NULL
);

CREATE TABLE `PRODUCTS` (
	`ID`	BIGINT	NOT NULL,
	`NAME`	VARCHAR(100)	NOT NULL,
	`PRICE`	VARCHAR(100)	NOT NULL,
	`STOCK`	VARCHAR(200)	NOT NULL,
	`DESCRIPTION`	TEXT	NOT NULL
);

ALTER TABLE `TASK_REQUESTS` ADD CONSTRAINT `PK_TASK_REQUESTS` PRIMARY KEY (
	`ID`,
	`USERS_ID`
);

ALTER TABLE `PAYMENTS` ADD CONSTRAINT `PK_PAYMENTS` PRIMARY KEY (
	`ID`,
	`ORDERS_ID`
);

ALTER TABLE `DELIVERYS` ADD CONSTRAINT `PK_DELIVERYS` PRIMARY KEY (
	`ID`,
	`ORDERS_ID`,
	`CONTRCTS_ID`
);

ALTER TABLE `CONTRACTS` ADD CONSTRAINT `PK_CONTRACTS` PRIMARY KEY (
	`ID`,
	`TASK_REQUEST_ID`,
	`TASK_HOPE_ID`
);

ALTER TABLE `IMAGES` ADD CONSTRAINT `PK_IMAGES` PRIMARY KEY (
	`ID`,
	`PRODUCTS_ID`,
	`TASK_REQUESTS_ID`
);

ALTER TABLE `USERS` ADD CONSTRAINT `PK_USERS` PRIMARY KEY (
	`ID`
);

ALTER TABLE `ORDERS` ADD CONSTRAINT `PK_ORDERS` PRIMARY KEY (
	`ID`,
	`PRODUCTS_ID`,
	`USERS_ID`
);

ALTER TABLE `TASK_HOPES` ADD CONSTRAINT `PK_TASK_HOPES` PRIMARY KEY (
	`ID`,
	`TASK_REQUESTS_ID`,
	`USERS_ID`
);

ALTER TABLE `PRODUCTS` ADD CONSTRAINT `PK_PRODUCTS` PRIMARY KEY (
	`ID`
);

ALTER TABLE `TASK_REQUESTS` ADD CONSTRAINT `FK_USERS_TO_TASK_REQUESTS_1` FOREIGN KEY (
	`USERS_ID`
)
REFERENCES `USERS` (
	`ID`
);

ALTER TABLE `PAYMENTS` ADD CONSTRAINT `FK_ORDERS_TO_PAYMENTS_1` FOREIGN KEY (
	`ORDERS_ID`
)
REFERENCES `ORDERS` (
	`ID`
);

ALTER TABLE `DELIVERYS` ADD CONSTRAINT `FK_ORDERS_TO_DELIVERYS_1` FOREIGN KEY (
	`ORDERS_ID`
)
REFERENCES `ORDERS` (
	`ID`
);

ALTER TABLE `DELIVERYS` ADD CONSTRAINT `FK_CONTRACTS_TO_DELIVERYS_1` FOREIGN KEY (
	`CONTRCTS_ID`
)
REFERENCES `CONTRACTS` (
	`ID`
);

ALTER TABLE `CONTRACTS` ADD CONSTRAINT `FK_TASK_REQUESTS_TO_CONTRACTS_1` FOREIGN KEY (
	`TASK_REQUEST_ID`
)
REFERENCES `TASK_REQUESTS` (
	`ID`
);

ALTER TABLE `CONTRACTS` ADD CONSTRAINT `FK_TASK_HOPES_TO_CONTRACTS_1` FOREIGN KEY (
	`TASK_HOPE_ID`
)
REFERENCES `TASK_HOPES` (
	`ID`
);

ALTER TABLE `IMAGES` ADD CONSTRAINT `FK_PRODUCTS_TO_IMAGES_1` FOREIGN KEY (
	`PRODUCTS_ID`
)
REFERENCES `PRODUCTS` (
	`ID`
);

ALTER TABLE `IMAGES` ADD CONSTRAINT `FK_TASK_REQUESTS_TO_IMAGES_1` FOREIGN KEY (
	`TASK_REQUESTS_ID`
)
REFERENCES `TASK_REQUESTS` (
	`ID`
);

ALTER TABLE `ORDERS` ADD CONSTRAINT `FK_PRODUCTS_TO_ORDERS_1` FOREIGN KEY (
	`PRODUCTS_ID`
)
REFERENCES `PRODUCTS` (
	`ID`
);

ALTER TABLE `ORDERS` ADD CONSTRAINT `FK_USERS_TO_ORDERS_1` FOREIGN KEY (
	`USERS_ID`
)
REFERENCES `USERS` (
	`ID`
);

ALTER TABLE `TASK_HOPES` ADD CONSTRAINT `FK_TASK_REQUESTS_TO_TASK_HOPES_1` FOREIGN KEY (
	`TASK_REQUESTS_ID`
)
REFERENCES `TASK_REQUESTS` (
	`ID`
);

ALTER TABLE `TASK_HOPES` ADD CONSTRAINT `FK_USERS_TO_TASK_HOPES_1` FOREIGN KEY (
	`USERS_ID`
)
REFERENCES `USERS` (
	`ID`
);
